// Worldwide country reference data used at registration: currency (drives
// `defaultCurrency`, see users.completeRegistration / localAuth.register)
// and calling code (drives the phone field's country-code prefix). Static,
// public ISO 3166 / ISO 4217 / E.164 reference data — not a live registry.
export interface CountryOption {
  code: string;
  name: string;
  currency: string;
  callingCode: string;
}

// Single alphabetical sequence (by name) across all continents — kept sorted
// so the registration dropdown lists countries in a predictable A→Z order.
export const COUNTRY_OPTIONS: CountryOption[] = [
  { code: "AF", name: "Afghanistan", currency: "AFN", callingCode: "93" },
  { code: "AL", name: "Albania", currency: "ALL", callingCode: "355" },
  { code: "DZ", name: "Algeria", currency: "DZD", callingCode: "213" },
  { code: "AD", name: "Andorra", currency: "EUR", callingCode: "376" },
  { code: "AO", name: "Angola", currency: "AOA", callingCode: "244" },
  { code: "AR", name: "Argentina", currency: "ARS", callingCode: "54" },
  { code: "AM", name: "Armenia", currency: "AMD", callingCode: "374" },
  { code: "AU", name: "Australia", currency: "AUD", callingCode: "61" },
  { code: "AT", name: "Austria", currency: "EUR", callingCode: "43" },
  { code: "AZ", name: "Azerbaijan", currency: "AZN", callingCode: "994" },
  { code: "BS", name: "Bahamas", currency: "BSD", callingCode: "1242" },
  { code: "BH", name: "Bahrain", currency: "BHD", callingCode: "973" },
  { code: "BD", name: "Bangladesh", currency: "BDT", callingCode: "880" },
  { code: "BB", name: "Barbados", currency: "BBD", callingCode: "1246" },
  { code: "BE", name: "Belgium", currency: "EUR", callingCode: "32" },
  { code: "BZ", name: "Belize", currency: "BZD", callingCode: "501" },
  { code: "BJ", name: "Benin", currency: "XOF", callingCode: "229" },
  { code: "BT", name: "Bhutan", currency: "BTN", callingCode: "975" },
  { code: "BO", name: "Bolivia", currency: "BOB", callingCode: "591" },
  { code: "BA", name: "Bosnia and Herzegovina", currency: "BAM", callingCode: "387" },
  { code: "BW", name: "Botswana", currency: "BWP", callingCode: "267" },
  { code: "BR", name: "Brazil", currency: "BRL", callingCode: "55" },
  { code: "BN", name: "Brunei", currency: "BND", callingCode: "673" },
  { code: "BG", name: "Bulgaria", currency: "BGN", callingCode: "359" },
  { code: "BF", name: "Burkina Faso", currency: "XOF", callingCode: "226" },
  { code: "BI", name: "Burundi", currency: "BIF", callingCode: "257" },
  { code: "CV", name: "Cabo Verde", currency: "CVE", callingCode: "238" },
  { code: "KH", name: "Cambodia", currency: "KHR", callingCode: "855" },
  { code: "CM", name: "Cameroon", currency: "XAF", callingCode: "237" },
  { code: "CA", name: "Canada", currency: "CAD", callingCode: "1" },
  { code: "CF", name: "Central African Republic", currency: "XAF", callingCode: "236" },
  { code: "TD", name: "Chad", currency: "XAF", callingCode: "235" },
  { code: "CL", name: "Chile", currency: "CLP", callingCode: "56" },
  { code: "CN", name: "China", currency: "CNY", callingCode: "86" },
  { code: "CO", name: "Colombia", currency: "COP", callingCode: "57" },
  { code: "KM", name: "Comoros", currency: "KMF", callingCode: "269" },
  { code: "CG", name: "Congo-Brazzaville", currency: "XAF", callingCode: "242" },
  { code: "CR", name: "Costa Rica", currency: "CRC", callingCode: "506" },
  { code: "CI", name: "Côte d'Ivoire", currency: "XOF", callingCode: "225" },
  { code: "HR", name: "Croatia", currency: "EUR", callingCode: "385" },
  { code: "CU", name: "Cuba", currency: "CUP", callingCode: "53" },
  { code: "CY", name: "Cyprus", currency: "EUR", callingCode: "357" },
  { code: "CZ", name: "Czechia", currency: "CZK", callingCode: "420" },
  { code: "DK", name: "Denmark", currency: "DKK", callingCode: "45" },
  { code: "DJ", name: "Djibouti", currency: "DJF", callingCode: "253" },
  { code: "DO", name: "Dominican Republic", currency: "DOP", callingCode: "1809" },
  { code: "CD", name: "DR Congo", currency: "CDF", callingCode: "243" },
  { code: "EC", name: "Ecuador", currency: "USD", callingCode: "593" },
  { code: "EG", name: "Egypt", currency: "EGP", callingCode: "20" },
  { code: "SV", name: "El Salvador", currency: "USD", callingCode: "503" },
  { code: "GQ", name: "Equatorial Guinea", currency: "XAF", callingCode: "240" },
  { code: "ER", name: "Eritrea", currency: "ERN", callingCode: "291" },
  { code: "SZ", name: "Eswatini", currency: "SZL", callingCode: "268" },
  { code: "EE", name: "Estonia", currency: "EUR", callingCode: "372" },
  { code: "ET", name: "Ethiopia", currency: "ETB", callingCode: "251" },
  { code: "FJ", name: "Fiji", currency: "FJD", callingCode: "679" },
  { code: "FI", name: "Finland", currency: "EUR", callingCode: "358" },
  { code: "FR", name: "France", currency: "EUR", callingCode: "33" },
  { code: "GA", name: "Gabon", currency: "XAF", callingCode: "241" },
  { code: "GM", name: "Gambia", currency: "GMD", callingCode: "220" },
  { code: "GE", name: "Georgia", currency: "GEL", callingCode: "995" },
  { code: "DE", name: "Germany", currency: "EUR", callingCode: "49" },
  { code: "GH", name: "Ghana", currency: "GHS", callingCode: "233" },
  { code: "GR", name: "Greece", currency: "EUR", callingCode: "30" },
  { code: "GT", name: "Guatemala", currency: "GTQ", callingCode: "502" },
  { code: "GN", name: "Guinea", currency: "GNF", callingCode: "224" },
  { code: "GW", name: "Guinea-Bissau", currency: "XOF", callingCode: "245" },
  { code: "GY", name: "Guyana", currency: "GYD", callingCode: "592" },
  { code: "HT", name: "Haiti", currency: "HTG", callingCode: "509" },
  { code: "HN", name: "Honduras", currency: "HNL", callingCode: "504" },
  { code: "HU", name: "Hungary", currency: "HUF", callingCode: "36" },
  { code: "IS", name: "Iceland", currency: "ISK", callingCode: "354" },
  { code: "IN", name: "India", currency: "INR", callingCode: "91" },
  { code: "ID", name: "Indonesia", currency: "IDR", callingCode: "62" },
  { code: "IR", name: "Iran", currency: "IRR", callingCode: "98" },
  { code: "IQ", name: "Iraq", currency: "IQD", callingCode: "964" },
  { code: "IE", name: "Ireland", currency: "EUR", callingCode: "353" },
  { code: "IL", name: "Israel", currency: "ILS", callingCode: "972" },
  { code: "IT", name: "Italy", currency: "EUR", callingCode: "39" },
  { code: "JM", name: "Jamaica", currency: "JMD", callingCode: "1876" },
  { code: "JP", name: "Japan", currency: "JPY", callingCode: "81" },
  { code: "JO", name: "Jordan", currency: "JOD", callingCode: "962" },
  { code: "KZ", name: "Kazakhstan", currency: "KZT", callingCode: "7" },
  { code: "KE", name: "Kenya", currency: "KES", callingCode: "254" },
  { code: "KW", name: "Kuwait", currency: "KWD", callingCode: "965" },
  { code: "KG", name: "Kyrgyzstan", currency: "KGS", callingCode: "996" },
  { code: "LA", name: "Laos", currency: "LAK", callingCode: "856" },
  { code: "LV", name: "Latvia", currency: "EUR", callingCode: "371" },
  { code: "LB", name: "Lebanon", currency: "LBP", callingCode: "961" },
  { code: "LS", name: "Lesotho", currency: "LSL", callingCode: "266" },
  { code: "LR", name: "Liberia", currency: "LRD", callingCode: "231" },
  { code: "LY", name: "Libya", currency: "LYD", callingCode: "218" },
  { code: "LI", name: "Liechtenstein", currency: "CHF", callingCode: "423" },
  { code: "LT", name: "Lithuania", currency: "EUR", callingCode: "370" },
  { code: "LU", name: "Luxembourg", currency: "EUR", callingCode: "352" },
  { code: "MG", name: "Madagascar", currency: "MGA", callingCode: "261" },
  { code: "MW", name: "Malawi", currency: "MWK", callingCode: "265" },
  { code: "MY", name: "Malaysia", currency: "MYR", callingCode: "60" },
  { code: "MV", name: "Maldives", currency: "MVR", callingCode: "960" },
  { code: "ML", name: "Mali", currency: "XOF", callingCode: "223" },
  { code: "MT", name: "Malta", currency: "EUR", callingCode: "356" },
  { code: "MR", name: "Mauritania", currency: "MRU", callingCode: "222" },
  { code: "MU", name: "Mauritius", currency: "MUR", callingCode: "230" },
  { code: "MX", name: "Mexico", currency: "MXN", callingCode: "52" },
  { code: "MD", name: "Moldova", currency: "MDL", callingCode: "373" },
  { code: "MC", name: "Monaco", currency: "EUR", callingCode: "377" },
  { code: "MN", name: "Mongolia", currency: "MNT", callingCode: "976" },
  { code: "ME", name: "Montenegro", currency: "EUR", callingCode: "382" },
  { code: "MA", name: "Morocco", currency: "MAD", callingCode: "212" },
  { code: "MZ", name: "Mozambique", currency: "MZN", callingCode: "258" },
  { code: "MM", name: "Myanmar", currency: "MMK", callingCode: "95" },
  { code: "NA", name: "Namibia", currency: "NAD", callingCode: "264" },
  { code: "NP", name: "Nepal", currency: "NPR", callingCode: "977" },
  { code: "NL", name: "Netherlands", currency: "EUR", callingCode: "31" },
  { code: "NZ", name: "New Zealand", currency: "NZD", callingCode: "64" },
  { code: "NI", name: "Nicaragua", currency: "NIO", callingCode: "505" },
  { code: "NE", name: "Niger", currency: "XOF", callingCode: "227" },
  { code: "NG", name: "Nigeria", currency: "NGN", callingCode: "234" },
  { code: "KP", name: "North Korea", currency: "KPW", callingCode: "850" },
  { code: "MK", name: "North Macedonia", currency: "MKD", callingCode: "389" },
  { code: "NO", name: "Norway", currency: "NOK", callingCode: "47" },
  { code: "OM", name: "Oman", currency: "OMR", callingCode: "968" },
  { code: "PK", name: "Pakistan", currency: "PKR", callingCode: "92" },
  { code: "PS", name: "Palestine", currency: "ILS", callingCode: "970" },
  { code: "PA", name: "Panama", currency: "PAB", callingCode: "507" },
  { code: "PG", name: "Papua New Guinea", currency: "PGK", callingCode: "675" },
  { code: "PY", name: "Paraguay", currency: "PYG", callingCode: "595" },
  { code: "PE", name: "Peru", currency: "PEN", callingCode: "51" },
  { code: "PH", name: "Philippines", currency: "PHP", callingCode: "63" },
  { code: "PL", name: "Poland", currency: "PLN", callingCode: "48" },
  { code: "PT", name: "Portugal", currency: "EUR", callingCode: "351" },
  { code: "QA", name: "Qatar", currency: "QAR", callingCode: "974" },
  { code: "RO", name: "Romania", currency: "RON", callingCode: "40" },
  { code: "RW", name: "Rwanda", currency: "RWF", callingCode: "250" },
  { code: "WS", name: "Samoa", currency: "WST", callingCode: "685" },
  { code: "SM", name: "San Marino", currency: "EUR", callingCode: "378" },
  { code: "ST", name: "São Tomé and Príncipe", currency: "STN", callingCode: "239" },
  { code: "SA", name: "Saudi Arabia", currency: "SAR", callingCode: "966" },
  { code: "SN", name: "Senegal", currency: "XOF", callingCode: "221" },
  { code: "RS", name: "Serbia", currency: "RSD", callingCode: "381" },
  { code: "SC", name: "Seychelles", currency: "SCR", callingCode: "248" },
  { code: "SL", name: "Sierra Leone", currency: "SLE", callingCode: "232" },
  { code: "SG", name: "Singapore", currency: "SGD", callingCode: "65" },
  { code: "SK", name: "Slovakia", currency: "EUR", callingCode: "421" },
  { code: "SI", name: "Slovenia", currency: "EUR", callingCode: "386" },
  { code: "SB", name: "Solomon Islands", currency: "SBD", callingCode: "677" },
  { code: "SO", name: "Somalia", currency: "SOS", callingCode: "252" },
  { code: "ZA", name: "South Africa", currency: "ZAR", callingCode: "27" },
  { code: "KR", name: "South Korea", currency: "KRW", callingCode: "82" },
  { code: "SS", name: "South Sudan", currency: "SSP", callingCode: "211" },
  { code: "ES", name: "Spain", currency: "EUR", callingCode: "34" },
  { code: "LK", name: "Sri Lanka", currency: "LKR", callingCode: "94" },
  { code: "SD", name: "Sudan", currency: "SDG", callingCode: "249" },
  { code: "SR", name: "Suriname", currency: "SRD", callingCode: "597" },
  { code: "SE", name: "Sweden", currency: "SEK", callingCode: "46" },
  { code: "CH", name: "Switzerland", currency: "CHF", callingCode: "41" },
  { code: "SY", name: "Syria", currency: "SYP", callingCode: "963" },
  { code: "TW", name: "Taiwan", currency: "TWD", callingCode: "886" },
  { code: "TJ", name: "Tajikistan", currency: "TJS", callingCode: "992" },
  { code: "TZ", name: "Tanzania", currency: "TZS", callingCode: "255" },
  { code: "TH", name: "Thailand", currency: "THB", callingCode: "66" },
  { code: "TL", name: "Timor-Leste", currency: "USD", callingCode: "670" },
  { code: "TG", name: "Togo", currency: "XOF", callingCode: "228" },
  { code: "TO", name: "Tonga", currency: "TOP", callingCode: "676" },
  { code: "TT", name: "Trinidad and Tobago", currency: "TTD", callingCode: "1868" },
  { code: "TN", name: "Tunisia", currency: "TND", callingCode: "216" },
  { code: "TR", name: "Turkey", currency: "TRY", callingCode: "90" },
  { code: "TM", name: "Turkmenistan", currency: "TMT", callingCode: "993" },
  { code: "UG", name: "Uganda", currency: "UGX", callingCode: "256" },
  { code: "UA", name: "Ukraine", currency: "UAH", callingCode: "380" },
  { code: "AE", name: "United Arab Emirates", currency: "AED", callingCode: "971" },
  { code: "GB", name: "United Kingdom", currency: "GBP", callingCode: "44" },
  { code: "US", name: "United States", currency: "USD", callingCode: "1" },
  { code: "UY", name: "Uruguay", currency: "UYU", callingCode: "598" },
  { code: "UZ", name: "Uzbekistan", currency: "UZS", callingCode: "998" },
  { code: "VU", name: "Vanuatu", currency: "VUV", callingCode: "678" },
  { code: "VA", name: "Vatican City", currency: "EUR", callingCode: "379" },
  { code: "VE", name: "Venezuela", currency: "VES", callingCode: "58" },
  { code: "VN", name: "Vietnam", currency: "VND", callingCode: "84" },
  { code: "YE", name: "Yemen", currency: "YER", callingCode: "967" },
  { code: "ZM", name: "Zambia", currency: "ZMW", callingCode: "260" },
  { code: "ZW", name: "Zimbabwe", currency: "ZWG", callingCode: "263" },
];

export function currencyForCountry(countryCode: string): string {
  return COUNTRY_OPTIONS.find((c) => c.code === countryCode)?.currency ?? "USD";
}

export function callingCodeForCountry(countryCode: string): string {
  return COUNTRY_OPTIONS.find((c) => c.code === countryCode)?.callingCode ?? "";
}
